### ISSUE TITLE
Add international support for Dutch/Nederlands (nl_NL)

### ISSUE THREAD

**Issue by andy5995** [andy5995/hldig#43]
@sexybiggetje, would you be interested in doing another translation?

https://github.com/andy5995/htdig/blob/6fde40d533d603b54ff2ef3ef997b0740a914837/po/messages.pot#L1

**Comment by andy5995** [comment]
@sexybiggetje this can be disregarded.

I learned about the Translation Project last night. It seems we don't need to do translations. I can still merge any in and they can be used for the next month or two. But after I have a complete English POT file, I can send it to the Translation project https://translationproject.org/html/welcome.html

**Comment by sexybiggetje** [comment]
Ok, was about to start :). But no problem, I can watch same tv now ;)

**Comment by andy5995** [comment]
@sexybiggetje , as with rmw, we'll be doing translations "in-house". Are you available to do an initial translation that I could use for testing?

**Comment by sexybiggetje** [comment]
Ofcourse, no problem.
