### ISSUE TITLE
'make uninstall' doesn't remove all files

### ISSUE THREAD

**Issue by andy5995** [andy5995/hldig#48]
These file don't get removed when `make uninstall` is run.

```
./bin/rundig
./htdocs/htdig/star_blank.gif
./htdocs/htdig/button8.gif
./htdocs/htdig/star_blank.png
./htdocs/htdig/star.gif
./htdocs/htdig/htdig.gif
./htdocs/htdig/button9.png
./htdocs/htdig/button5.png
./htdocs/htdig/button3.gif
./htdocs/htdig/button4.gif
./htdocs/htdig/button6.gif
./htdocs/htdig/button2.gif
./htdocs/htdig/button8.png
./htdocs/htdig/buttonl.gif
./htdocs/htdig/htdig.png
./htdocs/htdig/button5.gif
./htdocs/htdig/button1.png
./htdocs/htdig/button10.gif
./htdocs/htdig/button7.gif
./htdocs/htdig/button7.png
./htdocs/htdig/buttonl.png
./htdocs/htdig/search.html
./htdocs/htdig/button6.png
./htdocs/htdig/button1.gif
./htdocs/htdig/buttonr.png
./htdocs/htdig/star.png
./htdocs/htdig/button4.png
./htdocs/htdig/button9.gif
./htdocs/htdig/button10.png
./htdocs/htdig/buttonr.gif
./htdocs/htdig/button2.png
./htdocs/htdig/button3.png
./conf/HtFileType-magic.mime
./conf/htdig.conf
./conf/mime.types
./conf/cookies.txt
./share/htdig/wrapper.html
./share/htdig/short.html
./share/htdig/synonyms
./share/htdig/footer.html
./share/htdig/english.aff
./share/htdig/header.html
./share/htdig/syntax.html
./share/htdig/bad_words
./share/htdig/long.html
./share/htdig/english.0
./share/htdig/nomatch.html
./bin/HtFileType
```

One side effect of this problem is that if these files are altered in the source folder, they won't overwrite and update the files in the install directory the next time `make install` is run.

    installdir/*.html
    installdir/htdig.conf

**Comment by andy5995** [comment]
This requires the [Makefile.am](https://github.com/andy5995/hldig/blob/34c4af2b8fcf16a115791c7f10c965b33a9dc750/installdir/Makefile.am#L1) in installdir/ to have an uninstall target.

**Comment by solbu** [comment]
No, it requires the Makefile.am to _Not hardcode_ where it install these files.
I've fixed the files in bin/, and is working on the others.

Why are the images installed into ./htdocs/htdig/ ?
If one package this in, say, rpm, which have «--prefix /usr» the htdocs will end up in /usr/htdocs, when it belongs in /usr/share/hldig/htdocs.

**Comment by solbu** [comment]
I spoke too soon.
The install phase assumes the location where everything is installed is the location it will end up!

This is a flawed assumption. Unlike Debian, rpm packaging _does not_ use fakeroot, we use DESTDIR, and most of the conditional sec scripts are not executed as a result.
