### ISSUE TITLE
Using simplectemplate to generate the web site

### ISSUE THREAD

**Issue by andy5995** [andy5995/hldig#53]
I am seriously considering using [simplectemplate](https://github.com/dafky2000/simplectemplate) to generate the web site. @dafky2000, do you think sct would be suitable to generate a site similar to this one? https://andy5995.github.io/hldig

And do you suggest using the latest release? Any more big changes in your library scheduled? Should I wait a bit?

**Comment by dafky2000** [comment]
The biggest change is already committed to https://github.com/dafky2000/simplectemplate/tree/develop. `render_template` is replaced with `render_template2` and the former has been deleted.

I have 2 other big changes scheduled:
https://github.com/dafky2000/simplectemplate/issues/23
https://github.com/dafky2000/simplectemplate/issues/51

But these 2 new features should not affect the current template structure you are used to. Unless you want to take advantage of those features :)

**Comment by dafky2000** [comment]
Sorry, to answer your first question - I think https://github.com/dafky2000/simplectemplate would make a good fit. Especially once I get https://github.com/dafky2000/simplectemplate/issues/23 and https://github.com/dafky2000/simplectemplate/issues/51 done

**Comment by dafky2000** [comment]
Also, `develop` branch has removed the `data.` prefix from template variables. I still have to add options for utilizing https://github.com/dafky2000/simplectemplate/issues/24 which could be used to add it back in as part of the opening brace.

**Comment by dafky2000** [comment]
Sorry to be a pain Andy, but I just updated develop so it actually operates how I described above... If you would like to continue to use the `data.` prefix, you should use `my_render_template_file` which takes a struct input of options - take a look at https://github.com/dafky2000/simplectemplate/blob/4086d0c09cd6e5c087805efb693077a5c71859a2/spec/template_functions_render_template_file.c#L72

**Comment by andy5995** [comment]
Oh, no worries. I figured that might happen. I'll fix it up tomorrow. Thanks for the FYI.
