### ISSUE TITLE
home page doesn't validate

### ISSUE THREAD

**Issue by andy5995** [andy5995/hldig#81]
Fails the html validator:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fandy5995.github.io%2Fhldig%2F

The files that need to be edited are 

https://github.com/andy5995/hldig/blob/master/docs/templates/default.html

https://github.com/andy5995/hldig/blob/master/docs/assets/css/style.css

**Comment by 1sn0s** [comment]
Hi, may I work on this ?

**Comment by andy5995** [comment]
@1sn0s Would you like to work on this? Please let me know if you have any questions.

**Comment by AanjaneyaSinghDhoni** [comment]
i want to work on this. I' m a beginner and want to learn how to contribute on projects on github.

**Comment by andy5995** [comment]
Ok @AanjaneyaSinghDhoni , it appears that 1sn0s deleted his message and won't be working on this.

Thank you for the offer.

Please see https://github.com/andy5995/hldig/blob/master/CONTRIBUTING.md

And the README file in the docs/ directory.

**Comment by 1sn0s** [comment]
@andy5995 Sorry, I realized I might not be able to work on this on time. That is why I deleted my message.

**Comment by andy5995** [comment]
>Sorry, I realized I might not be able to work on this on time. That is why I deleted my message.

Hi @1sn0s . There was no time limit on it. And actually would only take about 20 minutes to complete. though it doesn't seem that way to people not familiar with how the site is generated; I'm sure it can seem a bit confusing. 

But thank you responding, and explaining :)

**Comment by 1sn0s** [comment]
oh ok. I looked at the code roughly and had the impression, it could be changing the broken html to CSS, but couldn't commit to building and fixing it. thankyou very much. I will probably check once it is fixed.

**Comment by jamessouth** [comment]
is this still open/available? i'm a beginner and i think i can fix this issue.

**Comment by andy5995** [comment]
Yes, @jamessouth .

**Comment by jamessouth** [comment]
ok i'll have something soon @andy5995
